language: c

before_install:
 - git submodule update --init --recursive

env:
  - LD_LIBRARY_PATH=.:rumpdyn/lib

script:
  - BUILD_QUIET=-qq ./buildnb.sh
  - make
  - ./rumprun ifconfig
  - ./rumprun sysctl kern.hostname
  - ./rumprun df

notifications:
  irc: "chat.freenode.net#rumpkernel-builds"
