language: c

before_install:
 - git submodule update --init --recursive

env:
  - LD_LIBRARY_PATH=.:rumpdyn/lib

script:
  - BUILD_QUIET=-qq ./buildnb.sh
  - make
  - ./rumprun ifconfig.so
  - ./rumprun sysctl.so kern.hostname
