language: c
os: linux
sudo: false

before_install:
 - git submodule update --init --recursive

matrix:
  include:
    - env: WITHZFS=false THREADING='fiber local' REALCC=gcc
      compiler: gcc
    - env: WITHZFS=false THREADING=pthread REALCC=gcc
      compiler: gcc
    - env: WITHZFS=true  THREADING='fiber local' REALCC=gcc
      compiler: gcc
    - env: WITHZFS=true  THREADING=pthread REALCC=gcc
      compiler: gcc
    - env: WITHZFS=false THREADING='fiber local' REALCC=clang-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
    - env: WITHZFS=false THREADING=pthread REALCC=clang-3.6
      addons: *clang36

script:
   - CC=$REALCC ./buildnb.sh -qq $(${WITHZFS} && echo zfs) ${THREADING} buildrump tests

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
